# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0de7c7f768e518990fea1a38eed3ad90173a62cffc033d37c5ef7e690fda2c91ee212f7201cfee6bc32caf0593012112eb6f366afd819c1e20c788cf79e13132

test:
  secret_key_base: 73066e73650cab8f4d20e5aa136fd0b344946719521d86f7f2ec60b6bcfb832e0736e19772c2bf3045ad46ff85d62688ff0fab8ac6bb2a55b92c4293ca1b00a2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
